# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sendMessageToPowerstream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1esendMessageToPowerstream.proto\")\n\x08setValue\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0e\n\x06value2\x18\x02 \x01(\x05\"\x8d\x02\n\tsetHeader\x12\x18\n\x05pdata\x18\x01 \x01(\x0b\x32\t.setValue\x12\x0b\n\x03src\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x65st\x18\x03 \x01(\x05\x12\r\n\x05\x64_src\x18\x04 \x01(\x05\x12\x0e\n\x06\x64_dest\x18\x05 \x01(\x05\x12\x12\n\ncheck_type\x18\x07 \x01(\x05\x12\x10\n\x08\x63md_func\x18\x08 \x01(\x05\x12\x0e\n\x06\x63md_id\x18\t \x01(\x05\x12\x10\n\x08\x64\x61ta_len\x18\n \x01(\x05\x12\x10\n\x08need_ack\x18\x0b \x01(\x05\x12\x0b\n\x03seq\x18\x0e \x01(\x05\x12\x0f\n\x07version\x18\x10 \x01(\x05\x12\x13\n\x0bpayload_ver\x18\x11 \x01(\x05\x12\x0c\n\x04\x66rom\x18\x17 \x01(\t\x12\x11\n\tdevice_sn\x18\x19 \x01(\t\"(\n\nsetMessage\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.setHeader')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sendMessageToPowerstream_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETVALUE._serialized_start=34
  _SETVALUE._serialized_end=75
  _SETHEADER._serialized_start=78
  _SETHEADER._serialized_end=347
  _SETMESSAGE._serialized_start=349
  _SETMESSAGE._serialized_end=389
# @@protoc_insertion_point(module_scope)
